#!/usr/bin/perl
#
#
# This is a super-hacky script to generate entry points from glext.h.
# I apologize to all those who are offended by the quality of this code.
# Cass Everitt
#
#
# I am modifying the original script to generate a simple file that includes
# header and source for an ES2 wrapper that provides only the entry points
# and limited enumerants via full OpenGL.

use FileHandle;

my $srcheader = <<END;

#if _WIN32 || __linux__
#include "r3/gl.h"
#include "r3/GL/entry.h"

#if _WIN32
# define r3GetProcAddress wglGetProcAddress
#elif __linux__
# include <GL/glx.h>
# define r3GetProcAddress( proc ) glXGetProcAddress( (const GLubyte *) proc )
#endif

namespace r3 {
END

if ( scalar( @ARGV ) != 1 ) {
   print "\nusage: glext_entry.pl <glext.h_file>\n";
   print join " ", @ARGV;
   print "\n";
}

my $glext = new FileHandle;
$glext->open( "<$ARGV[0]" );

open( GLEXT, "<$ARGV[0]" );


my %entries;

my $line;
while( $line = <GLEXT> ) {

  if ( $line =~ /GLAPI (.*) APIENTRY (gl[A-Za-z0-9]+)\s*(\(.*\))/ ) {
      my $returnType = $1;
      my $entryPoint = $2;
      my $args = $3;
      my %h;
      $h{ "entry" } = $entryPoint;
      $h{ "return" } = $returnType;
      $h{ "args" } = $args;
      $entries{ $entryPoint } = { "entry" => $entryPoint, "return" => $returnType, "args" => $args };
  }

}

$glext->close();

write_header();
write_source();


sub write_disclaimer($) {
	my $fp = shift;

	print $fp "// Generated by glext_entry.pl, modify at your own peril.\n"; 
	print $fp "// Cass Everitt\n\n";   

}


sub write_header {
	my $fp  = new FileHandle;
	$fp->open( ">_entry.h" );

	write_disclaimer( $fp );

	print $fp "#ifndef __R3_GL_ENTRY_H__\n";
	print $fp "#define __R3_GL_ENTRY_H__\n";

	print $fp "\n\n";
	print $fp "#if _WIN32 || __linux__\n\n";
	print $fp "#include \"glext.h\"\n\n";

	print $fp "namespace r3 {\n\n";
	
	foreach my $e ( sort keys %entries ) {
		my $ue = uc( $e );
		print $fp "    extern PFN" . $ue . "PROC $e;\n";
	}
	print $fp "\n\n";
	print $fp "    void InitGLEntry();\n\n";
	print $fp "\n}\n\n";

	print $fp "\n\n";
	print $fp "#endif // _WIN32 || __linux__\n\n";
	print $fp "#endif // __R3_GL_ENTRY_H__\n\n";
	
	close ( $fp );

}

sub write_source {
	my $fp  = new FileHandle;
	$fp->open( ">_entry.cpp" );

	write_disclaimer( $fp );

        print $fp $srcheader;

        foreach my $e ( sort keys %entries ) {
          my $ue = uc( $e );
          print $fp "    PFN" . $ue . "PROC $e;\n";
        }

        print $fp "\n\n";
	print $fp "    void InitGLEntry() {\n\n";
	foreach my $e ( sort keys %entries ) {
		my $ue = uc( $e );
		print $fp "        $e = (PFN" . $ue . "PROC) r3GetProcAddress( \"$e\" );\n";
	}
	print $fp "\n    }\n\n";

	print $fp "\n}\n\n";

	print $fp "\n\n";
	print $fp "#endif // _WIN32 || __linux__\n\n";
	
	close ( $fp );

}




